import { bool, int, isoDay, jsonField, num } from "./primitives.js";
import { frontendCategoryId } from "../utils/categories.js";

/**
 * Company/agency projection.
 *
 * Field names follow the public `companies` fixture the marketplace components
 * already read: `companySlug`, `displayName`, `logo`, `coverImage`,
 * `membershipStatus`, `verificationStatus`, `categoriesAllowed`, `leadChannels`.
 */
export function serializeCompany(row, { serviceAreas = [], languages = [], categories = [], licenses = [] } = {}) {
  return {
    id: row.public_id,
    organizationId: String(row.id),
    companySlug: row.slug,
    slug: row.slug,
    kind: row.kind,
    legalName: row.legal_name || row.name,
    displayName: row.name,
    name: row.name,
    country: row.country_name || null,
    countrySlug: row.country_slug || null,
    state: row.state_name || null,
    city: row.city_name || null,
    logo: row.logo_url || null,
    coverImage: row.cover_image_url || null,
    description: row.description || "",
    tagline: row.tagline || null,
    address: [row.address_line1, row.address_line2, row.city_name, row.country_name].filter(Boolean).join(", ") || null,
    serviceAreas,
    languages,
    website: row.website_url || null,
    email: row.email || null,
    phone: row.phone || null,
    whatsapp: row.whatsapp || null,
    emailVerified: Boolean(row.email),
    phoneVerified: Boolean(row.phone),
    foundedYear: int(row.founded_year),
    employeeCount: int(row.employee_count),
    membershipStatus: row.status === "active" ? "active" : row.status,
    status: row.status,
    verificationStatus: row.verification_status === "verified" ? "approved" : row.verification_status,
    verifiedAt: isoDay(row.verified_at),
    documentsSubmitted: licenses.length > 0 || row.verification_status !== "unverified",
    publicPageEnabled: bool(row.is_publicly_visible),
    verifiedBadgeEnabled: row.verification_status === "verified",
    featured: bool(row.is_featured),
    categoriesAllowed: categories.map((category) => frontendCategoryId(category.root_category_id)).filter(Boolean),
    countryCategoriesAllowed: categories.length > 0,
    leadChannels: [
      row.email ? "email" : null,
      row.phone ? "phone" : null,
      row.whatsapp ? "whatsapp" : null,
      row.website_url ? "website" : null,
    ].filter(Boolean),
    licenses: licenses.map((license) => ({
      number: license.license_number,
      authority: license.authority_name || null,
      expiresAt: isoDay(license.expires_at),
      status: license.status,
    })),
    listingCount: int(row.listing_count) ?? 0,
    activeListingCount: int(row.active_listing_count) ?? 0,
    agentCount: int(row.agent_count) ?? 0,
    reviewCount: int(row.review_count) ?? 0,
    rating: num(row.rating_avg),
    responseTimeMinutes: int(row.response_time_minutes),
    socialLinks: jsonField(row.social_links, {}),
    seo: { title: row.seo_title || row.name, description: row.seo_description || row.tagline || null },
    explicitDenyFlags: [],
    createdAt: isoDay(row.created_at),
    updatedAt: isoDay(row.updated_at),
  };
}

/** Agent/professional projection matching the public `agents` fixture. */
export function serializeAgent(row, { languages = [], specialties = [], serviceAreas = [], categories = [] } = {}) {
  return {
    id: row.public_id,
    agentId: String(row.id),
    organizationId: row.organization_id ? String(row.organization_id) : null,
    organizationSlug: row.organization_slug || null,
    organizationName: row.organization_name || null,
    slug: row.slug,
    fullName: row.display_name,
    firstName: row.first_name,
    lastName: row.last_name,
    role: row.title || "Advisor",
    tagline: row.seo_description || row.title || null,
    photo: row.photo_url || "",
    biography: row.bio || "",
    yearsOfExperience: int(row.experience_years),
    languages,
    specialties,
    serviceAreas,
    categories: categories.map((category) => frontendCategoryId(category.root_category_id)).filter(Boolean),
    email: row.email || "",
    phone: row.phone || "",
    whatsapp: row.whatsapp || "",
    website: row.organization_website || null,
    leadChannels: [
      row.email ? "email" : null,
      row.phone ? "phone" : null,
      row.whatsapp ? "whatsapp" : null,
    ].filter(Boolean),
    licenseNumber: row.license_number || null,
    activeListingCount: int(row.active_listing_count) ?? 0,
    listingCount: int(row.listing_count) ?? 0,
    reviewCount: int(row.review_count) ?? 0,
    rating: num(row.rating_avg),
    responseRate: num(row.response_rate),
    responseTimeMinutes: int(row.response_time_minutes),
    publicProfileEnabled: bool(row.is_publicly_visible),
    status: row.status,
    verificationStatus: row.verification_status,
    featured: bool(row.is_featured),
    joinedAt: isoDay(row.joined_at),
    socialLinks: jsonField(row.social_links, {}),
    explicitDenyFlags: [],
  };
}
